In [ ]:
#7-1
import pandas as pd

score = pd.Series([30, 20, 40, pd.NA, 30, pd.NA])
print(score, '\n')
print(score.sum(), '\n')
print(score.mean(), '\n')
print(score + 5, '\n')

print(pd.isna(score), '\n')
print(pd.isna(score).sum(), '\n')

print(score.size, '\n')
print(score.count(), '\n')

print(pd.notna(score), '\n')
print(pd.notna(score).sum(), '\n')

score = score.dropna()
print(score, '\n')
score = score.reset_index(drop=True)
print(score, '\n')



0      30
1      20
2      40
3    <NA>
4      30
5    <NA>
dtype: object 

120 

30.0 

0      35
1      25
2      45
3    <NA>
4      35
5    <NA>
dtype: object 

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool 

2 

6 

4 

0     True
1     True
2     True
3    False
4     True
5    False
dtype: bool 

4 

0    30
1    20
2    40
4    30
dtype: object 

0    30
1    20
2    40
3    30
dtype: object 



In [ ]:
#7-2
import pandas as pd
import numpy as np

df = pd.read_csv('../data/iris.csv')
df.iloc[0, 1] = pd.NA ; df.iloc[0, 2] = pd.NA
df.iloc[1, 2] = np.nan; df.iloc[2, 3] = None
print(df.head(), '\n')

print(df.isnull().sum(), '\n')
print(df.isnull().sum(axis = 1), '\n')
print(df.loc[df.isnull().sum(axis = 1) > 0, :], '\n')

df = df.dropna()
df = df.reset_index(drop = True)
print(df.head())


   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa 

Sepal_Length    0
Sepal_Width     1
Petal_Length    2
Petal_Width     1
Species         0
dtype: int64 

0      2
1      1
2      1
3      0
4      0
      ..
145    0
146    0
147    0
148    0
149    0
Length: 150, dtype: int64 

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa 

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           4.6          3.1           1.5          0.2  set

In [14]:
#7-3
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler

df_org = pd.read_csv('../data/iris.csv')
df_miss = df_org.copy()

df_miss.iloc[0, 3] = pd.NA; df_miss.iloc[0, 2] = pd.NA
df_miss.iloc[1, 2] = None ; df_miss.iloc[2, 3] = None
print(df_miss.head(4), '\n')

scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df_miss.iloc[:, :4])
print(df_scaled[0:5, :], '\n')

imputer = KNNImputer(n_neighbors = 5)
df_scaled = imputer.fit_transform(df_scaled)
print(df_scaled[0:5, :], '\n')

df_filled = scaler.inverse_transform(df_scaled)
print(df_filled[0:5, :], '\n')

df_miss.iloc[:, :4] = df_filled

print(df_miss.head(4), '\n')
print(df_org.head(4), '\n')

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           NaN          NaN  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa
3           4.6          3.1           1.5          0.2  setosa 

[[0.22222222 0.625             nan        nan]
 [0.16666667 0.41666667        nan 0.04166667]
 [0.11111111 0.5        0.05084746        nan]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]] 

[[0.22222222 0.625      0.0779661  0.09166667]
 [0.16666667 0.41666667 0.08474576 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]] 

[[5.1  3.5  1.46 0.32]
 [4.9  3.   1.5  0.2 ]
 [4.7  3.2  1.3  0.2 ]
 [4.6  3.1  1.5  0.2 ]
 [5.   3.6  1.4  0.2 ]] 

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1     

In [18]:
#7-4
import pandas as pd
import numpy as np
from scipy import stats

df = pd.read_csv('../data/iris.csv')
sw = df.Sepal_Width

z = np.abs(stats.zscore(sw))
outliers = sw[z > 2]
print(outliers, '\n')

Q1 = sw.quantile(0.25)
Q3 = sw.quantile(0.75)
IQR = Q3 - Q1

outliers = sw[(sw < Q1 - IQR * 1.5) | (sw > Q3 + IQR * 1.5)]
print(outliers, '\n')

clean = sw.loc[~sw.isin(outliers)]
print(len(clean))

14    4.0
15    4.4
32    4.1
33    4.2
60    2.0
Name: Sepal_Width, dtype: float64 

15    4.4
32    4.1
33    4.2
60    2.0
Name: Sepal_Width, dtype: float64 

146


In [ ]:
import pandas as pd

df = pd.read_csv('../data/iris.csv')

df_sorted = df.sort_values('Sepal_Length');
print(df_sorted.head(10), '\n')

df_sorted = df.sort_values('Sepal_Length', ascending = False)
print(df_sorted.head(10), '\n')

df_sorted = df.sort_values(['Species', 'Sepal_Width'])
print(df_sorted.head(10), '\n')

print(df['Petal_Length'].rank().astype(int), '\n')
print(df['Petal_Length'].rank(ascending = False).astype(int), '\n')

    Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
13           4.3          3.0           1.1          0.1  setosa
8            4.4          2.9           1.4          0.2  setosa
42           4.4          3.2           1.3          0.2  setosa
38           4.4          3.0           1.3          0.2  setosa
41           4.5          2.3           1.3          0.3  setosa
22           4.6          3.6           1.0          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
6            4.6          3.4           1.4          0.3  setosa
47           4.6          3.2           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa 

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
131           7.9          3.8           6.4          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117    

In [24]:
#7-7

import pandas as pd
import itertools

df = pd.read_csv('../data/iris.csv')

df20 = df.sample(n = 20, random_state = 123)
print(df20, '\n')

stratified = df.groupby('Species').apply(
    lambda x : x.sample(frac = 0.2, random_state = 123)
)
print(stratified, '\n')

species = df.Species.unique()

comb = list(itertools.combinations(species, 2))
print(comb, '\n')

df_agg = df.groupby('Species').mean()
print(df_agg, '\n')

df_agg = df.groupby('Species').std()
print(df_agg, '\n')



     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species
72            6.3          2.5           4.9          1.5  versicolor
112           6.8          3.0           5.5          2.1   virginica
132           6.4          2.8           5.6          2.2   virginica
88            5.6          3.0           4.1          1.3  versicolor
37            4.9          3.6           1.4          0.1      setosa
138           6.0          3.0           4.8          1.8   virginica
87            6.3          2.3           4.4          1.3  versicolor
42            4.4          3.2           1.3          0.2      setosa
8             4.4          2.9           1.4          0.2      setosa
90            5.5          2.6           4.4          1.2  versicolor
141           6.9          3.1           5.1          2.3   virginica
33            5.5          4.2           1.4          0.2      setosa
59            5.2          2.7           3.9          1.4  versicolor
116           6.5   

In [ ]:
import pandas as pd

df1 = pd.DataFrame([[169, 58, 1.0],
                    [172, 73, 1.2],
                    [184, 82, 0.7]],
                   columns=['height', 'weight', 'eye'])
df2 = pd.DataFrame([[176, 71, 0.8, 'M'],
                    [169, 62, 0.7, 'F'],
                    [158, 60, 1.3, 'M']],
                   columns=['height', 'weight', 'eye', 'gender'])
df3 = pd.DataFrame([[3, 22],
                    [2, 21]],
                   columns=['grade', 'age'])

print(df1, '\n')
print(df2, '\n')
print(df3, '\n')

df12 = pd.concat([df1, df2])
print(df12, '\n')
df12 = df12.reset_index(drop=True)
print(df12, '\n')

df13 = pd.concat([df1, df3], axis = 1)
print(df13, '\n')



   height  weight  eye
0     169      58  1.0
1     172      73  1.2
2     184      82  0.7 

   height  weight  eye gender
0     176      71  0.8      M
1     169      62  0.7      F
2     158      60  1.3      M 

   grade  age
0      3   22
1      2   21 

   height  weight  eye gender
0     169      58  1.0    NaN
1     172      73  1.2    NaN
2     184      82  0.7    NaN
0     176      71  0.8      M
1     169      62  0.7      F
2     158      60  1.3      M 

   height  weight  eye gender
0     169      58  1.0    NaN
1     172      73  1.2    NaN
2     184      82  0.7    NaN
3     176      71  0.8      M
4     169      62  0.7      F
5     158      60  1.3      M 

   height  weight  eye  grade   age
0     169      58  1.0    3.0  22.0
1     172      73  1.2    2.0  21.0
2     184      82  0.7    NaN   NaN 



In [26]:
import pandas as pd

df1 = pd.DataFrame([['a', 90], ['b', 80], ['c', 40]],
                   columns=['name', 'kor'])
df2 = pd.DataFrame([['a', 75], ['b', 60], ['d', 90]],
                   columns=['name', 'math'])

print(df1, '\n')
print(df2, '\n')

df12 = df1.merge(df2, on = 'name')
print(df12, '\n')

df12 = df1.merge(df2, how = 'left', on = 'name')
print(df12, '\n')

df12 = df1.merge(df2, how = 'right', on = 'name')
print(df12, '\n')

df12 = df1.merge(df2, how = 'outer', on = 'name')
print(df12, '\n')

  name  kor
0    a   90
1    b   80
2    c   40 

  name  math
0    a    75
1    b    60
2    d    90 

  name  kor  math
0    a   90    75
1    b   80    60 

  name  kor  math
0    a   90  75.0
1    b   80  60.0
2    c   40   NaN 

  name   kor  math
0    a  90.0    75
1    b  80.0    60
2    d   NaN    90 

  name   kor  math
0    a  90.0  75.0
1    b  80.0  60.0
2    c  40.0   NaN
3    d   NaN  90.0 



In [27]:
import seaborn as sns

df = sns.load_dataset('tips')
print(df.head(), '\n')

p1 = df.pivot_table(index = 'sex', columns = 'day', values = 'total_bill', aggfunc = 'mean')
print(p1.head(), '\n')

p2 = df.pivot_table(index = 'sex', columns = 'time', values = 'total_bill', aggfunc = 'mean')
print(p2.head(), '\n')

p3 = df.pivot_table(index = 'time', columns = 'day', values = 'tip', aggfunc = 'max')

print(p3.head(), '\n')

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4 

day          Thur        Fri        Sat        Sun
sex                                               
Male    18.714667  19.857000  20.802542  21.887241
Female  16.715312  14.145556  19.680357  19.872222 

time        Lunch     Dinner
sex                         
Male    18.048485  21.461452
Female  16.339143  19.213077 

day     Thur   Fri   Sat  Sun
time                         
Lunch    6.7  3.48   NaN  NaN
Dinner   3.0  4.73  10.0  6.5 

