In [ ]:
#7-1
import pandas as pd

score = pd.Series([30, 20, 40, pd.NA, 30, pd.NA])
print(score, '\n')
print(score.sum(), '\n')
print(score.mean(), '\n')
print(score + 5, '\n')

print(pd.isna(score), '\n')
print(pd.isna(score).sum(), '\n')

print(score.size, '\n')
print(score.count(), '\n')

print(pd.notna(score), '\n')
print(pd.notna(score).sum(), '\n')

score = score.dropna()
print(score, '\n')
score = score.reset_index(drop=True)
print(score, '\n')



0      30
1      20
2      40
3    <NA>
4      30
5    <NA>
dtype: object 

120 

30.0 

0      35
1      25
2      45
3    <NA>
4      35
5    <NA>
dtype: object 

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool 

2 

6 

4 

0     True
1     True
2     True
3    False
4     True
5    False
dtype: bool 

4 

0    30
1    20
2    40
4    30
dtype: object 

0    30
1    20
2    40
3    30
dtype: object 



In [ ]:
#7-2
import pandas as pd
import numpy as np

df = pd.read_csv('../data/iris.csv')
df.iloc[0, 1] = pd.NA ; df.iloc[0, 2] = pd.NA
df.iloc[1, 2] = np.nan; df.iloc[2, 3] = None
print(df.head(), '\n')

print(df.isnull().sum(), '\n')
print(df.isnull().sum(axis = 1), '\n')
print(df.loc[df.isnull().sum(axis = 1) > 0, :], '\n')

df = df.dropna()
df = df.reset_index(drop = True)
print(df.head())


   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa 

Sepal_Length    0
Sepal_Width     1
Petal_Length    2
Petal_Width     1
Species         0
dtype: int64 

0      2
1      1
2      1
3      0
4      0
      ..
145    0
146    0
147    0
148    0
149    0
Length: 150, dtype: int64 

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa 

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           4.6          3.1           1.5          0.2  set

In [ ]:
#7-3
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler

df_org = pd.read_csv('../data/iris.csv')
df_miss = df_org.copy()

df_miss.iloc[0, 3] = pd.NA; df_miss.iloc[0, 2] = pd.NA
df_miss.iloc[1, 2] = None ; df_miss.iloc[2, 3] = None
print(df_miss.head(4), '\n')

scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df_miss.iloc[:, :4])
print(df_scaled[0:5, :], '\n')

imputer = KNNImputer(n_neighbors = 5)
df_scaled = imputer.fit_transform(df_scaled)
print(df_scaled[0:5, :], '\n')

df_filled = scaler.inverse_transform(df_scaled)
print(df_filled[0:5, :], '\n')

df_miss.iloc[:, :4] = df_filled

print(df_miss.head(4), '\n')
print(df_org.head(4), '\n')

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           NaN          NaN  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa
3           4.6          3.1           1.5          0.2  setosa 

[[0.22222222 0.625             nan        nan]
 [0.16666667 0.41666667        nan 0.04166667]
 [0.11111111 0.5        0.05084746        nan]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]] 

[[0.22222222 0.625      0.0779661  0.09166667]
 [0.16666667 0.41666667 0.08474576 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]] 

[[5.1  3.5  1.46 0.32]
 [4.9  3.   1.5  0.2 ]
 [4.7  3.2  1.3  0.2 ]
 [4.6  3.1  1.5  0.2 ]
 [5.   3.6  1.4  0.2 ]]
   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1       