In [9]:
import numpy as np

arr1 = np.array([10, 100, 1000])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)

arr2 = np.array ([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(type(arr2))
print(arr2.dtype)
print(arr2.shape)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

print(arr2.sum())
print(arr2.sum(axis = 0))
print(arr2.sum(axis = 1))
print(arr2.max())
print(arr2.max(axis = 0))
print(arr2.max(axis = 1))

[  10  100 1000]
<class 'numpy.ndarray'>
int64
(3,)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
[[  11  102 1003]
 [  14  105 1006]]
[[  9  98 997]
 [  6  95 994]]
[[  10  200 3000]
 [  40  500 6000]]
[[ 10.          50.         333.33333333]
 [  2.5         20.         166.66666667]]
21
[5 7 9]
[ 6 15]
6
[4 5 6]
[3 6]
