In [2]:
import pandas as pd

age = pd.Series([25, 34, 19, 45, 60])
print(age)
print(type(age))

data = ['spring', 'summer', 'autumn', 'winter']
season = pd.Series(data)
print(data, type(data))
print(season, type(season))

print(season.iloc[2])

0    25
1    34
2    19
3    45
4    60
dtype: int64
<class 'pandas.Series'>
['spring', 'summer', 'autumn', 'winter'] <class 'list'>
0    spring
1    summer
2    autumn
3    winter
dtype: str <class 'pandas.Series'>
autumn


In [3]:
import pandas as pd
score = pd.DataFrame([[85, 96, 40, 95],
                     [73, 69, 45, 80],
                     [78, 50, 60, 90]])
print(score)
print(type(score))
print(score.index)
print(score.columns)

print(score.iloc[1, 2])

    0   1   2   3
0  85  96  40  95
1  73  69  45  80
2  78  50  60  90
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=4, step=1)
45


In [4]:
import pandas as pd
import numpy as np

np1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print (np1)
print(type(np1))

df1 = pd.DataFrame(np1)
print(df1)
print(type(df1))


np2 = df1.to_numpy()
print(np2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
<class 'pandas.DataFrame'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import pandas as pd

age = pd.Series([25, 34, 19, 45])
print(age)
age.index = ['John', 'Jane', 'Tom', 'Luka']
print(age)

print(age.iloc[2])
print(age.loc['Tom'])

score = pd.DataFrame([[85, 96, 40, 95], [73, 69, 45, 80], [78, 50, 60, 90]])

print(score)
score.index = ['John', 'Jane', 'Tom']
score.columns = ['KOR', 'ENG', 'MATH', 'SCI']
print(score)

print(score.iloc[2, 1])
print(score.loc['Tom', 'ENG'])

0    25
1    34
2    19
3    45
dtype: int64
John    25
Jane    34
Tom     19
Luka    45
dtype: int64
19
19
    0   1   2   3
0  85  96  40  95
1  73  69  45  80
2  78  50  60  90
      KOR  ENG  MATH  SCI
John   85   96    40   95
Jane   73   69    45   80
Tom    78   50    60   90
50
50


In [6]:
age = pd.Series([25, 34, 19, 45, 60])
age.index = ['John', 'Jane', 'Tom', 'Micle', 'Tom']
print(age)

print(age.iloc[3])
print(age.loc['Tom'])

John     25
Jane     34
Tom      19
Micle    45
Tom      60
dtype: int64
45
Tom    19
Tom    60
dtype: int64


In [24]:
population = pd.Series([523, 675, 690, 720, 800])
print(population)
population.index = [2021, 2022, 2023, 2024, 2025]
print(population)

0    523
1    675
2    690
3    720
4    800
dtype: int64
2021    523
2022    675
2023    690
2024    720
2025    800
dtype: int64
